image: gitpod/workspace-full:latest
privileged: true
github:
  prebuilds:
    # Enable prebuilds for each push to master
    master: true
    # Used to prebuilt the workspace for merge requests
    pullRequestsFromForks: true
    addLabel: gitpod-ready
    addComment: true
