stages:
  - build
  - test

.build-template: &build-template
  stage: build
  image: paludis/${DISTRIBUTION}-${COMPILER}:${VERSION}
  script:
    - mkdir -pv build-obj && cd build-obj
    - ../ci/configure-paludis.sh .. ${DISTRIBUTION} ${COMPILER}
    - ninja -j$(nproc) all
  cache: &build_artifact_cache
    key: build-${DISTRIBUTION}-${COMPILER}-${VERSION}
    paths:
      - build-obj/

.test-template: &test-template
  stage: test
  image: paludis/${DISTRIBUTION}-${COMPILER}:${VERSION}
  cache: *build_artifact_cache
  script:
    - cd build-obj
    - ctest -V

build:exherbo:
  variables:
    DISTRIBUTION: "exherbo"
    COMPILER: "gcc"
    VERSION: "latest"
  <<: *build-template

test:exherbo:
  variables:
    DISTRIBUTION: "exherbo"
    COMPILER: "gcc"
    VERSION: "latest"
  dependencies:
    - build:exherbo
  <<: *test-template

build:exherbo-clang:
  variables:
    DISTRIBUTION: "exherbo"
    COMPILER: "clang"
    VERSION: "latest"
  <<: *build-template

test:exherbo-clang:
  variables:
    DISTRIBUTION: "exherbo"
    COMPILER: "clang"
    VERSION: "latest"
  dependencies:
    - build:exherbo-clang
  allow_failure: true
  <<: *test-template

build:gentoo:
  variables:
    DISTRIBUTION: "gentoo"
    COMPILER: "gcc"
    VERSION: "latest"
  <<: *build-template

test:gentoo:
  variables:
    DISTRIBUTION: "gentoo"
    COMPILER: "gcc"
    VERSION: "latest"
  dependencies:
    - build:gentoo
  <<: *test-template

